#!/bin/bash

set -euo pipefail

log() {
    echo "$(date '+[%Y-%m-%d %H:%M:%S]') $*"
}

# Job spec config

# Fetch UAA token
log "Fetching token from UAA at ${UAA_API_URL}"
UAA_REQUEST=$(curl --fail --max-time 10 -s -k -X POST ${UAA_API_URL}/oauth/token --data "client_id=${UAA_CLIENT_ID}&client_secret=${UAA_CLIENT_SECRET}&grant_type=client_credentials&response_type=token")
UAA_TOKEN=$(echo ${UAA_REQUEST} | jq -r .access_token)

# Find the routing group GUID. Assumes the first one is a TCP router.
log "Fetching routing groups from CF at: ${CLOUD_FOUNDRY_API_URL}"
ROUTING_GROUP_REQ=$(curl --fail --max-time 10 -s -H "Authorization: bearer ${UAA_TOKEN}" -k ${CLOUD_FOUNDRY_API_URL}/routing/v1/router_groups)
ROUTING_GROUP_GUID=$(echo ${ROUTING_GROUP_REQ} | jq -r .[0].guid )

# Register the route
ROUTE="[{\"router_group_guid\":\"${ROUTING_GROUP_GUID}\",\"backend_port\":${BACKEND_PORT},\"backend_ip\":\"${BACKEND_IP}\",\"port\":${KUBO_PORT}, \"ttl\": 60}]"
log "Announcing route: '${ROUTE}'"
curl --fail --max-time 10 -s -H "Authorization: bearer ${UAA_TOKEN}" -X POST -k ${CLOUD_FOUNDRY_API_URL}/routing/v1/tcp_routes/create -d "${ROUTE}"
log "Route announced"

